#!/bin/bash
# Generate the Generative Sequence LaTeX table from engine output.
#
# Usage:
#   ./scripts/gen_latex_table.sh [output.tex]
#
# Runs `cabal run ab-initio -- --structural --csv /tmp/pen_table.csv`
# and converts the CSV to a LaTeX tabular fragment.
# If output.tex is given, writes there; otherwise prints to stdout.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CSV_FILE="/tmp/pen_gen_table_$$.csv"
OUTPUT="${1:-/dev/stdout}"

cd "$PROJECT_DIR/engine"

echo "Running ab-initio in structural mode..." >&2
cabal run ab-initio -- --structural --csv "$CSV_FILE" >/dev/null 2>&1

echo "Generating LaTeX table..." >&2

# Structure names with LaTeX formatting
declare -A TEX_NAMES=(
  [Universe]='Universe $\U_0$'
  [Unit]='Unit type $\mathbf{1}$'
  [Witness]='Witness $\star : \mathbf{1}$'
  [Pi]='$\Pi$/$\Sigma$ types'
  [S1]='Circle $S^1$'
  [Trunc]='Propositional truncation'
  [S2]='Sphere $S^2$'
  [S3]='$S^3 \cong \mathrm{SU}(2)$'
  [Hopf]='Hopf fibration'
  [Cohesion]='Cohesion'
  [Connections]='Connections'
  [Curvature]='Curvature tensors'
  [Metric]='Metric + frame bundle'
  [Hilbert]='Hilbert functional'
  [DCT]='Dynamical Cohesive Topos'
)

# Cumulative tau values (tau_n = F_{n+2} - 1 for d=2)
TAU=(1 2 4 7 12 20 33 54 88 143 232 376 609 986 1596)

{
  echo '% AUTO-GENERATED by scripts/gen_latex_table.sh'
  echo '% Source: cabal run ab-initio -- --structural'
  echo "% Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo '\begin{tabular}{@{}cr l rrrr rrr@{}}'
  echo '\toprule'
  echo '$n$ & $\tau$ & Structure & $\Delta_n$ & $\nu$ & $\kappa$ & $\rho$ & $\Phi_n$ & $\Omega_{n-1}$ & Bar \\'
  echo '\midrule'

  # Track cumulative sums for Omega computation
  sum_nu=0
  sum_k=0
  prev_delta=0

  # Read CSV (skip header)
  tail -n +2 "$CSV_FILE" | while IFS=, read -r step name nu kappa rho bar delta source cands k_desugar k_entry k_bitcost; do
    # Look up LaTeX name
    tex_name="${TEX_NAMES[$name]:-$name}"
    tau="${TAU[$((step - 1))]}"

    # Compute Phi_n = Delta_n / Delta_{n-1}
    if [ "$step" -eq 1 ]; then
      phi_str="---"
      omega_str="---"
      bar_str="---"
    else
      if [ "$prev_delta" -gt 0 ]; then
        phi_str=$(printf "%.2f" "$(echo "scale=4; $delta / $prev_delta" | bc)")
      else
        phi_str="---"
      fi
      if [ "$sum_k" -gt 0 ]; then
        omega_str=$(printf "%.2f" "$(echo "scale=4; $sum_nu / $sum_k" | bc)")
      else
        omega_str="---"
      fi
      bar_str=$(printf "%.2f" "$bar")
    fi

    # Format rho (ensure leading zero)
    rho_fmt=$(printf "%.2f" "$rho")

    printf '%-2s & %-4s & %-32s & %-3s & %-3s & %s & %-5s & %-4s & %-4s & %-4s \\\\\n' \
      "$step" "$tau" "$tex_name" "$delta" "$nu" "$kappa" "$rho_fmt" "$phi_str" "$omega_str" "$bar_str"

    # Update running sums
    sum_nu=$((sum_nu + nu))
    sum_k=$((sum_k + kappa))
    prev_delta="$delta"
  done

  echo '\bottomrule'
  echo '\end{tabular}'
} > "$OUTPUT"

rm -f "$CSV_FILE"

if [ "$OUTPUT" != "/dev/stdout" ]; then
  echo "LaTeX table written to $OUTPUT" >&2
fi
