from __future__ import annotations

import csv
import json
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
ENGINE_DIR = ROOT / "engine"
OUT_DIR = ROOT / "runs" / "review_hardening"


@dataclass(frozen=True)
class RunConfig:
    key: str
    label: str
    extra_args: list[str]


RUNS = [
    RunConfig("baseline", "Baseline strict lane", []),
    RunConfig("max_rho", "Greedy max-rho selector", ["--max-rho"]),
    RunConfig("topo_linear", "Linear topological bonus", ["--topo-bonus-mode", "linear"]),
    RunConfig("topo_none", "No topological dimension bonus", ["--topo-bonus-mode", "none"]),
]


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def float_or_none(value: str | None) -> float | None:
    if value is None or value == "":
        return None
    return float(value)


def int_or_none(value: str | None) -> int | None:
    if value is None or value == "":
        return None
    return int(value)


def normalize_name(row: dict[str, str]) -> str:
    return row.get("selected_name") or row.get("name") or ""


def run_one(cfg: RunConfig) -> dict[str, Any]:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    csv_path = OUT_DIR / f"{cfg.key}.csv"
    prefix_path = OUT_DIR / f"{cfg.key}_prefix.csv"
    log_path = OUT_DIR / f"{cfg.key}.log"
    cmd = [
        "cabal",
        "run",
        "ab-initio",
        "--",
        "--strict",
        "--skip-validation",
        "--skip-mcts",
        "--max-steps",
        "15",
        "--csv",
        str(csv_path),
        "--prefix-report",
        str(prefix_path),
        *cfg.extra_args,
    ]
    with log_path.open("w", encoding="utf-8") as log_handle:
        proc = subprocess.run(
            cmd,
            cwd=ENGINE_DIR,
            stdout=log_handle,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
        )
    rows = read_csv_rows(csv_path) if csv_path.exists() else []
    prefix_rows = read_csv_rows(prefix_path) if prefix_path.exists() else []
    return {
        "key": cfg.key,
        "label": cfg.label,
        "command": cmd,
        "exit_code": proc.returncode,
        "csv_path": str(csv_path),
        "prefix_path": str(prefix_path),
        "log_path": str(log_path),
        "rows": rows,
        "prefix_rows": prefix_rows,
    }


def divergence_against(
    baseline_rows: list[dict[str, str]],
    candidate_rows: list[dict[str, str]],
) -> dict[str, Any]:
    baseline_by_step = {int(row["step"]): row for row in baseline_rows}
    candidate_by_step = {int(row["step"]): row for row in candidate_rows}
    all_steps = sorted(set(baseline_by_step) | set(candidate_by_step))
    for step in all_steps:
        base = baseline_by_step.get(step)
        cand = candidate_by_step.get(step)
        if base is None or cand is None:
            return {
                "step": step,
                "baseline": normalize_name(base or {}),
                "candidate": normalize_name(cand or {}),
            }
        if normalize_name(base) != normalize_name(cand):
            return {
                "step": step,
                "baseline": normalize_name(base),
                "candidate": normalize_name(cand),
            }
    return {"step": None, "baseline": "", "candidate": ""}


def completion_summary(rows: list[dict[str, str]]) -> dict[str, Any]:
    if not rows:
        return {"steps": 0, "last_name": "", "last_rho": None}
    last = rows[-1]
    return {
        "steps": len(rows),
        "last_name": normalize_name(last),
        "last_rho": float_or_none(last.get("rho")),
    }


def build_markdown(results: list[dict[str, Any]]) -> str:
    baseline = next(result for result in results if result["key"] == "baseline")
    baseline_rows = baseline["rows"]
    baseline_prefix = baseline["prefix_rows"]
    lines: list[str] = []
    lines.append("# Review Hardening Ablations")
    lines.append("")
    lines.append("Generated by `scripts/run_review_hardening_ablations.py`.")
    lines.append("")
    lines.append("## Run Matrix")
    lines.append("")
    lines.append("| Run | Exit | Completed steps | First divergence vs baseline | Last selected step |")
    lines.append("| --- | --- | --- | --- | --- |")
    for result in results:
        summary = completion_summary(result["rows"])
        div = divergence_against(baseline_rows, result["rows"])
        if result["key"] == "baseline":
            div_label = "baseline"
        elif div["step"] is None:
            div_label = "none"
        else:
            div_label = f"step {div['step']} ({div['baseline']} -> {div['candidate']})"
        lines.append(
            f"| {result['label']} | {result['exit_code']} | {summary['steps']} | {div_label} | {summary['last_name']} |"
        )
    lines.append("")
    lines.append("## Baseline Search Telemetry")
    lines.append("")
    lines.append("| Step | Selected | Raw candidates | Deduped | Viable | Source |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for row in baseline_prefix:
        lines.append(
            "| {step} | {name} | {raw} | {deduped} | {viable} | {source} |".format(
                step=row.get("step", ""),
                name=row.get("selected_name", ""),
                raw=row.get("raw_candidates", ""),
                deduped=row.get("deduped_candidates", ""),
                viable=row.get("viable_candidates", ""),
                source=row.get("selected_source", ""),
            )
        )
    lines.append("")
    lines.append("## Selection Objective Ablation")
    lines.append("")
    max_rho = next(result for result in results if result["key"] == "max_rho")
    max_div = divergence_against(baseline_rows, max_rho["rows"])
    lines.append(
        "Greedy `max-rho` first diverges at "
        + (
            f"step {max_div['step']}, where baseline selects `{max_div['baseline']}` and greedy selects `{max_div['candidate']}`."
            if max_div["step"] is not None
            else "no step."
        )
    )
    lines.append("")
    lines.append("## Topological Bonus Sensitivity")
    lines.append("")
    lines.append("| Mode | Completed steps | First divergence vs baseline | Last selected step |")
    lines.append("| --- | --- | --- | --- |")
    for key in ("topo_linear", "topo_none"):
        result = next(item for item in results if item["key"] == key)
        summary = completion_summary(result["rows"])
        div = divergence_against(baseline_rows, result["rows"])
        div_label = "none" if div["step"] is None else f"step {div['step']} ({div['baseline']} -> {div['candidate']})"
        lines.append(
            f"| {result['label']} | {summary['steps']} | {div_label} | {summary['last_name']} |"
        )
    lines.append("")
    lines.append("## Commands")
    lines.append("")
    for result in results:
        cmd = " ".join(result["command"])
        lines.append(f"- `{result['label']}`: `{cmd}`")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    results = [run_one(cfg) for cfg in RUNS]
    report_path = OUT_DIR / "ablation_report.md"
    json_path = OUT_DIR / "ablation_report.json"
    report = build_markdown(results)
    report_path.write_text(report, encoding="utf-8")
    json_path.write_text(json.dumps(results, indent=2), encoding="utf-8")
    print(report)
    print()
    print(f"Markdown report written to {report_path}")
    print(f"JSON report written to {json_path}")


if __name__ == "__main__":
    main()
